name: Rust CI

on:
    push: 
        branches: 
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: Set up Rust
              uses: actions/checkout@v2
            - name: Install cargo-audit
              run: cargo install cargo-audit
            - name: Build
              run: cargo build --verbose
            - name: Test
              run: cargo test --verbose
            - name: Clippy
              run: cargo clippy --verbose -- -D warnings
            - name: Audit
              run: cargo audit

            - run: git fetch --all --tags
            - name: Check Release Version
              uses: thebongy/version-check@v2
              with:
                file: Cargo.toml 
              id: version_check_staging
            - name:
              run: |
                echo "Version ${{steps.version_check_staging.outputs.releaseVersion}}"
            - uses: actions-ecosystem/action-push-tag@v1
              with:
                tag: ${{ steps.version_check_staging.outputs.releaseVersion }}